### ISSUE TITLE
Stuck on Running Inference with htdemucs 6s on an RTX 5070, Can't Halt Process

### ISSUE THREAD

**Issue by woofmute** [Anjok07/ultimatevocalremovergui#1900]
I have upgraded my GPU finally from an Nvidia GTX 980Ti to an RTX 5070 and now UVR gets stuck on 'Running Inference' at 5% when using GPU acceleration with htdemucs 6s. This used to run fine on my GTX 980Ti. Now I cannot use UVR to split anything.

While it is running inference, task manager claims minimal CPU usage for the process and 0% GPU usage. I get no error messages about the running process, but if I try to halt the process it will then get stuck halting process forever.

The log in the window at that point is this:

```
File 1/1 "06. Air Towel.flac".

File 1/1 Loading model (htdemucs_6s)... Done!
File 1/1 Running inference...

Process stopped by user.

```
Despite that, at that point the button to start a new split is still saying "Halting process please wait...".
I then have to end process in task manager or UVR will not let me close it, because it wants me to wait for it to halt running processes first.

Specs:
CPU: AMD Ryzen 9 7900 12-Core Processor 3.70 GHz
RAM: 32.0 GB (31.1 GB usable)
Graphics Card: NVIDIA GeForce RTX 5070 (12 GB)
Graphics Driver Version: 576.88
OS: Windows 10 (22H2)

Edit: Did not see the beta release until now, trying it and we are getting past 5% on running inference but it seems quite slow in comparison to the older GPU. With the beta, it took 00:17:20 to complete... and has produced a really bad split that is not accurate and has occasional loud static bursts throughout that do not exist in the source song. Never had it behave like that before.

**Comment by deton24** [comment]
Anjok released a new UVR Roformer patch fixing CUDA for RTX 5000 Series GPUs and Windows users (it’s based on CUDA 12.6 and newer PyTorch). 
Be aware, that it might be potentially not backward-compatible with older NVIDIA GPUs, and AMD/Intel GPUs using DirectML. [Download](https://www.mediafire.com/file_premium/4jg10r9wa3tujav/UVR_Patch_4_24_25_20_11_BETA_full_cuda_12.8.zip/file)

For torch dynamo issues with certain models using this patch [read](https://github.com/Anjok07/ultimatevocalremovergui/issues/2127#issuecomment-4482871304).

**Comment by blackbeerrr** [comment]
Can u upload pls UVR_Patch_4_24_25_20_11_BETA_full_cuda_12.8 in github with patch fixing in information about repository
on mediafie i see slow download  approach 6 mb\s under 36 mb\s speed download ?

**Comment by Lily754** [comment]
> Anjok released a new UVR Roformer patch fixing CUDA for RTX 5000 Series GPUs and Windows users (it’s based on CUDA 12.6 and newer PyTorch). It might be potentially not backward compatible with older GPUs, so be aware. [Download](https://www.mediafire.com/file_premium/4jg10r9wa3tujav/UVR_Patch_4_24_25_20_11_BETA_full_cuda_12.8.zip/file)

Wow, thank you so much! That totally fixed it!
9800x3d + 5070Ti

**Comment by LIQUIDMIND111** [comment]
> > Anjok released a new UVR Roformer patch fixing CUDA for RTX 5000 Series GPUs and Windows users (it’s based on CUDA 12.6 and newer PyTorch). It might be potentially not backward compatible with older GPUs, so be aware. [Download](https://www.mediafire.com/file_premium/4jg10r9wa3tujav/UVR_Patch_4_24_25_20_11_BETA_full_cuda_12.8.zip/file)
> 
> Wow, thank you so much! That totally fixed it! 9800x3d + 5070Ti

i down loaded it also, now what? just run the EXE or copy paste to the UVR folder? and all the bins....?

**Comment by deton24** [comment]
If you had a previous UVR installation, the installer should rather detect it and overwrite everything in order to make it just work, but in case of any issues, uninstall UVR, and perform clean installation of the binary in that MediaFire link.

**Comment by QuasiRus** [comment]
> Anjok released a new UVR Roformer patch fixing CUDA for RTX 5000 Series GPUs and Windows users (it’s based on CUDA 12.6 and newer PyTorch). Be aware, that it might be potentially not backward-compatible with older NVIDIA GPUs, and AMD/Intel GPUs using DirectML. [Download](https://www.mediafire.com/file_premium/4jg10r9wa3tujav/UVR_Patch_4_24_25_20_11_BETA_full_cuda_12.8.zip/file)

I have RTX5070 and CUDA 12.**9** instead of 12.**8** and it worked for me, thank you.

**Comment by LIQUIDMIND111** [comment]
Yes worked!!!

"It was from the Mind of GOD, the Universe was created."
- - -- --- -)( ((---IMAGINATION IS CREATION---)) )(- --- -- - -
           - -- -- --- -)( ((---liquid[)(]mind---)) )(- --- -- -- -

**Comment by Jbla0712** [comment]
Thanks 
Working 

April 2026

**Comment by moisespedrozaedicion** [comment]
Thanks, it fixed it.
April 2026

**Comment by Hanhui-Huang** [comment]
Thanks a lot. I got the same problem, and  the patch works to upgrade UVR_1_15_25_22_30_BETA with 5070Ti.

May 2026
