### ISSUE TITLE
UVR-MDX-NET Main is not using GPU

### ISSUE THREAD

**Issue by MikuAuahDark** [Anjok07/ultimatevocalremovergui#500]
It looks like UVR-MDX-NET Main is not using GPU at all. It adds slight VRAM usage but process everything using CPU. This can be proven by checking "GPU Conversion", perform inference, and checking the usage through `nvidia-smi` which is minimal.

Compared to 3_HP-Vocal-UVR (VR Architecture) which uses GPU and can finish inference in less than a minute.

I'm running UVR in Windows with RTX 3060 Laptop GPU.

**Comment by code-decider** [comment]
it may be intended because there are also non cuda users who will be using this ,they can propaly add gpu accerlation if they want  to becozin demucs lib there is a option gpu acceration for cuda gpu's only

**Comment by HazySkies** [comment]
Linux Mint user here, and I have the same issue for ALL of the UVR-MDX-NET models. 

On top of that it's been using up over 12GBs of ram when converting, which at best closes UVR and fails to complete, and at worse causes my entire PC to lockup and force a restart risking system wide data corruption.

**Comment by bjh021149** [comment]
reintsall gpu driver

**Comment by bjh021149** [comment]
> reintsall gpu driver

That works with my tesla P40，you may give it a try

**Comment by MikuAuahDark** [comment]
Have you checked the GPU utilization? Yes it will increase VRAM usage, but no real GPU usage when inferencing.

**Comment by Ph0rk0z** [comment]
Same here on 3090 on linux. Loads like 300mb to GPU, occasional blip of 5%, multi core CPU usage. VR models use GPU memory and time. Demucs I have to check again.

**Comment by zharvz** [comment]
Same here. VR models can use GPU and it's blazing fast (3060). MDX always use only CPU. onnxruntine and onnxruntine-gpu is installed, 1.15.1. I even removed onnxruntime to force it use only gpu but it didn't worked.

**Comment by marshalleq** [comment]
And here was me about to go down a python hunt for what requirements I haven't met.  Thank goodness I read this first.

**Comment by kdcyberdude** [comment]
Any update here? Any idea why MDX models are not able to utilise the GPU?

**Comment by WineWG** [comment]
I am experiencing this problem too with MDX models.

**Comment by WineWG** [comment]
I solved this, took me long enough and I'm not sure which one of these steps was the correct one but here is basically everything I did:

I think the problem lied in a wrong CUDA version. You need to have cuda 11.6, check if your GPU is compatible [here ](https://en.wikipedia.org/wiki/CUDA#GPUs_supported)

1. Uninstall CUDA if you have it installed 
2. Uninstall Ultimate Vocal Remover and be sure to delete the folder it lives in
3. Install CUDA version 11.6 
4. Install cuDDN version 8.5.0.96 (Windows)
5. Install pytorch https://pytorch.org/get-started/locally/
6. reinstall ultimate vocal remover

 **install CUDA**
https://developer.nvidia.com/cuda-downloads
**how to install cuddn**
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installdriver-windows
and when u copy the cuddn .dll files to the CUDA folder be sure to put the lib files in both the lib/x64 folder and the lib folder.

**Comment by marshalleq** [comment]
Python=drama.  Thankgoodness for Anaconda, but even that doesn't get all the way.

Thanks for the feedback I will try on linux next couple of days hopefully.

**Comment by Ph0rk0z** [comment]
>11.6.

Oh dear.. that's not a fix. Maybe if this is the only software you run. Whatever it uses needs to be recompiled.

**Comment by MikuAuahDark** [comment]
@WineWG Most of the time you **don't need** to install CUDA and cuDNN if you installed PyTorch. If you follow PyTorch installation from their page, it already has CUDA and cuDNN bundled.

**Comment by AngusGhoul** [comment]
any solution? still have this annoying problem, I have a fuckin good gpu and the uvr is not using it when it´s was working beofre

**Comment by Anjok07** [comment]
@AngusGhoul I just updated the application to address this issue. Please download or redownload he latest patch

**Comment by apchernavsky** [comment]
Same here. 
installed everything as @femfii suggested.
Reinstalled UVR and latest patch.
run python -c "import torch; print(torch.cuda.is_available())  returns True
but no success 

Nvidia RTX 3060

**Comment by charliesxia** [comment]
it's works on 4060ti ,GPU utilization will increase after a few minutes

**Comment by apchernavsky** [comment]
> it's works on 4060ti ,GPU utilization will increase after a few minutes

strange behaviour but
you are right!
thanks

**Comment by ken107** [comment]
Well, it's 2026 and I asked Codex for help. It's weird though, when I reinstall onnxruntime-gpu as suggested, it reinstalled the same version, but it worked. No code change.

> • The issue is not your GPU checkbox. It is the MDX runtime stack.
> 
>   What I confirmed locally:
> 
>   - PyTorch sees the GPU: torch.cuda.is_available = True
>   - MDX ONNX does not: onnxruntime.get_available_providers() = ['AzureExecutionProvider', 'CPUExecutionProvider']
>   - Both onnxruntime and onnxruntime-gpu are installed in the same .venv
> 
>   Why that matters:
> 
>   - UVR’s MDX ONNX path in separate.py:490 asks ONNX Runtime for CUDAExecutionProvider.
>   - But the runtime only exposes CPU, so MDX falls back to CPU.
>   - VR models still use PyTorch in separate.py:1051, so VR can use GPU while MDX cannot. That matches the symptom in issue #500.
> 
>   Likely root cause:
> 
>   - onnxruntime and onnxruntime-gpu are conflicting in the same env.
>   - Your current ORT install is not actually loading the CUDA provider, even though the GPU wheel is present.
> 
>   What to do:
> 
>   ./.venv/bin/python -m pip uninstall -y onnxruntime onnxruntime-gpu
>   ./.venv/bin/python -m pip install --upgrade "onnxruntime-gpu[cuda,cudnn]"
> 
>   Then verify:
> 
>   ./.venv/bin/python -c "import torch, onnxruntime as ort; print(torch.cuda.is_available()); print(ort.get_available_providers())"
> 
>   You want to see CUDAExecutionProvider in that list.
> 
>   If it still does not appear, the next suspect is missing CUDA/cuDNN runtime libs for ORT, but your PyTorch/ORT versions are broadly compatible with ONNX Runtime’s
>   CUDA 12.x / cuDNN 9 guidance:
> 
>   - Issue context: https://github.com/Anjok07/ultimatevocalremovergui/issues/500
>   - ORT CUDA provider docs: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html
> 
>   If you want, I can also patch separate.py to emit a clear warning when MDX is set to GPU but ORT has no CUDAExecutionProvider, so this failure is obvious at
>   runtime.
> 
> 
> › patch it
