### ISSUE TITLE
RuntimeError: "cuFFT error: CUFFT_INTERNAL_ERROR" on RTX4090 Debian based distro

### ISSUE THREAD

**Issue by MSVstudios** [Anjok07/ultimatevocalremovergui#746]
installed with standard Linux procedure
if using GPU conversion, RuntimeError: "cuFFT error: CUFFT_INTERNAL_ERROR" is triggered
On the base system CUDA toolkit 11.8 is installed

Solution
install inside an Anaconda env using standard Linux procedure
then
```
pip uninstall torch
pip uninstall nvidia-cublas-cu11
pip uninstall nvidia-cuda-nvrtc-cu11   
pip uninstall nvidia-cuda-runtime-cu11 
pip uninstall nvidia-cuda-runtime-cu11
pip uninstall torchmetrics

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install torchmetrics
```
working flowless.

hope can be helpful to other people:

**Comment by DrMWeigand** [comment]
Thanks you very much for providing a solution for the problem. I want to remark that it is also crucial to initialize your conda environment as follows: 

```
conda create --name uvr2 python=3.9
conda install cudatoolkit=11.8
```

After taking the provided steps I did a pip freeze. I'll leave the output requirements.txt attached which might save you the hassle to take the additional steps. [](url)
[requirements.txt](https://github.com/Anjok07/ultimatevocalremovergui/files/12536271/requirements.txt)

**Comment by nonoo** [comment]
I fixed this issue the following way:

```
pip uninstall torch -y
pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu118
```
